#[macro_use]
extern crate serde;

#[macro_use]
/// custom made logging macros
pub mod logging;
pub mod buffer;
/// TLS certificates
pub mod certificate;
/// channels used for communication between main process and workers
pub mod channel;
/// used to parse TOML config and generate requests from it
pub mod config;
pub mod parser;
/// contains Rust types generated by the protobuf definition
pub mod proto;
pub mod ready;
/// all types received by Sōzu
pub mod request;
/// all types sent by Sōzu
pub mod response;
/// sockets used to pass file descriptors
pub mod scm_socket;
/// representation of Sōzu's state
pub mod state;
pub mod writer;
